---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-redis
  labels:
    app: demoapp
    component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
      component: redis
  template:
    metadata:
      labels:
        app: demoapp
        component: redis
    spec:
      restartPolicy: Always
      containers:
        - name: redis
          image: redis:4.0.9
          livenessProbe:
            tcpSocket:
              port: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
          command:
            - redis-server
            - --appendonly
            - "yes"
