---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demoapp-mysql
  labels:
    app: demoapp
    component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
