---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "demoapp.mysql.name" . }}
  labels:
    app: {{ template "demoapp.name" . }}
    chart: {{ template "demoapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.storage.size }}
  storageClassName: {{ .Values.mysql.storage.className }}