---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "demoapp.mysql-env.name" . }}
data:
  MYSQL_PASSWORD: {{ .Values.env.secret.MYSQL_PASSWORD | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.env.secret.MYSQL_ROOT_PASSWORD | b64enc }}
