---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "demoapp.puma.name" . }}
  labels:
    app: {{ template "demoapp.name" . }}
    chart: {{ template "demoapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: puma
spec:
  ports:
    - protocol: TCP
      port: 3000
  selector:
    app: {{ template "demoapp.name" . }}
    release: {{ .Release.Name }}
    component: puma
