---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "demoapp.rails-env.name" . }}
data:
  SECRET_KEY_BASE: {{ .Values.env.secret.SECRET_KEY_BASE | b64enc }}
  MYSQL_PASSWORD: {{ .Values.env.secret.MYSQL_PASSWORD | b64enc }}
