---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "demoapp.setup-db.name" . }}
  labels:
    app: {{ template "demoapp.name" . }}
    chart: {{ template "demoapp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: {{ template "demoapp.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: setup-db
          image: {{ .Values.rails.image.repository }}:{{ .Values.rails.image.setupDbTag }}
          command:
            - ./bin/setup-db
          envFrom:
            - configMapRef:
                name: {{ template "demoapp.rails-env.name" . }}
            - secretRef:
                name: {{ template "demoapp.rails-env.name" . }}
